// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://noecoscfvriqubfyuyns.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vZWNvc2NmdnJpcXViZnl1eW5zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExNTM2NzEsImV4cCI6MjA2NjcyOTY3MX0.lqrSe82lKmdedIUBWYnPQE-XOUXQO5psV5cbdVo5W5g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);